application: bot-telegram-gae-test
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: telegram-python.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
